# Generated by Django 3.2.12 on 2022-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=250, verbose_name='Image URL')),
                ('amount_show', models.CharField(max_length=250, verbose_name='Amount of show')),
                ('categories', models.TextField(verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
